["stripe_to_file.destination.filesystem"]
bucket_url = "file:.dlt/extract_files/stripe_extract_files"

["sqlite_to_file.destination.filesystem"]
bucket_url = "file:.dlt/extract_files/sqlite_extract_files"
