[test.destination.filesystem]
bucket_url = "file:.dlt/extract_files/test"

[stripe_to_file.destination.filesystem]
bucket_url = "file:.dlt/extract_files/stripe_to_file"

[sqlite_to_file.destination.filesystem]
bucket_url = "file:.dlt/extract_files/sqlite_to_file"

